/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/62ko27ezCw4
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function homeBrowse() {
  return (
    <div className="grid lg:grid-cols-4 items-start max-w-7xl mx-auto px-4 py-6 gap-6">
      <div className="space-y-4 lg:col-span-3">
        <header className="space-y-2">
          <h1 className="text-3xl font-bold">DEX Coins</h1>
          <p className="text-gray-500 dark:text-gray-400">Discover and trade tokens on decentralized exchanges.</p>
        </header>
        <div className="flex items-center justify-between">
          <nav className="flex items-center space-x-4">
            <Link
              className="font-medium text-base rounded-lg px-3 py-2 text-center hover:bg-gray-100 dark:hover:bg-gray-800"
              href="#"
            >
              All
            </Link>
            <Link
              className="font-medium text-base rounded-lg px-3 py-2 text-center hover:bg-gray-100 dark:hover:bg-gray-800"
              href="#"
            >
              DeFi
            </Link>
            <Link
              className="font-medium text-base rounded-lg px-3 py-2 text-center hover:bg-gray-100 dark:hover:bg-gray-800"
              href="#"
            >
              NFT
            </Link>
            <Link
              className="font-medium text-base rounded-lg px-3 py-2 text-center hover:bg-gray-100 dark:hover:bg-gray-800"
              href="#"
            >
              Metaverse
            </Link>
          </nav>
          <div className="flex items-center space-x-2">
            <Label className="sr-only" htmlFor="search">
              Search
            </Label>
            <div className="w-60">
              <Input id="search" placeholder="Search..." />
            </div>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 rounded-lg overflow-hidden">
              <img
                alt="Token"
                aspectRatio="1"
                height="64"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width="64"
              />
            </div>
            <div className="space-y-1.5">
              <h2 className="font-semibold">Uniswap</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                UNI is the governance token for Uniswap, a popular decentralized exchange.
              </p>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 rounded-lg overflow-hidden">
              <img
                alt="Token"
                aspectRatio="1"
                height="64"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width="64"
              />
            </div>
            <div className="space-y-1.5">
              <h2 className="font-semibold">SushiSwap</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                SUSHI is the governance token for SushiSwap, a community-run automated market maker.
              </p>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 rounded-lg overflow-hidden">
              <img
                alt="Token"
                aspectRatio="1"
                height="64"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width="64"
              />
            </div>
            <div className="space-y-1.5">
              <h2 className="font-semibold">Aave</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                AAVE is the governance and utility token of the Aave protocol.
              </p>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 rounded-lg overflow-hidden">
              <img
                alt="Token"
                aspectRatio="1"
                height="64"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width="64"
              />
            </div>
            <div className="space-y-1.5">
              <h2 className="font-semibold">Compound</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                COMP is the governance token for the Compound protocol.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="space-y-4">
        <div className="flex items-center space-x-4">
          <div className="font-medium">Category</div>
          <Link
            className="text-sm font-medium rounded-lg px-2 py-1 text-center hover:bg-gray-100 dark:hover:bg-gray-800"
            href="#"
          >
            All
          </Link>
          <Link
            className="text-sm font-medium rounded-lg px-2 py-1 text-center hover:bg-gray-100 dark:hover:bg-gray-800"
            href="#"
          >
            DeFi
          </Link>
          <Link
            className="text-sm font-medium rounded-lg px-2 py-1 text-center hover:bg-gray-100 dark:hover:bg-gray-800"
            href="#"
          >
            NFT
          </Link>
          <Link
            className="text-sm font-medium rounded-lg px-2 py-1 text-center hover:bg-gray-100 dark:hover:bg-gray-800"
            href="#"
          >
            Metaverse
          </Link>
        </div>
      </div>
    </div>
  )
}
